title: Note page
context:
  label: default
variants:
    - name: default
      label: Note
      context:
        post-actions: yes
        footer: yes
        note-text: |
          <p>The last 7 days Iâ€™ve progressed more in the redesign of my personal website than the last 2 years where I kind of started.</p>
          <p>I wanted big blocks of time. It didnâ€™t work. The excuse, lack of time.</p>
          <p>Now Iâ€™m doing a MVP redesign and work on it everyday even when I only have 15min.</p>
        meta-type:
        - meta-link: yes
          post-meta: lang
          lang: EspaÃ±ol
        - post-meta: weather
          weather: 73.82Â°F
        - meta-link: yes
          post-meta: location
          location: 51Â° N, 0Â° E
        - meta-link: yes
          post-meta: responses
          responses: 7
        tag-item:
        - tag: Personal site
        - tag: Redesign
        - tag: Progression
        likes: 4
        comments: 2
        reposts: 1
    - name: like
      label: Like
      context:
        footer: yes
        note-text: |
          Liked a <a href="#">tweet</a> by <a href="#">ben_rosen</a>
        meta-type:
        - meta-link: yes
          post-meta: responses
          responses: 2
        comments: 2
    - name: link
      label: Link
      context:
        footer: yes
        post-actions: yes
        link: yes
        note-type: link
        context-url: https://leportella.com/why-have-a-blog.html
        link-title: Why you should have a blog (and write in it) | Leticia Portella
        context-text: Having your independent blog is an excellent way to share what you think in a decentralized way, independent of any major company that may add a paywall to it.
        note-text: |
          Never get tired of this kind of posts, theyâ€™re so inspiring.
        meta-type:
        - post-meta: weather
          weather: 73.82Â°F
        - meta-link: yes
          post-meta: responses
          responses: 3
        - meta-link: yes
          post-meta: location
          location: 51Â° N, 0Â° E
        - meta-link: yes
          post-meta: lang
          lang: EspaÃ±ol
        tag-item:
        - tag: Indieweb
        - tag: Blogs
        likes: 2
        comments: 1
    - name: reply
      label: Reply
      context:
        reply: yes
        footer: yes
        post-actions: yes
        context-avatar: https://media.ramiroruiz.com/avatars/ramiroruiz/1130549139165634566/4SXqYSCJ_bigger.png
        context-url: https://twitter.com/ramiroruiz/status/1355129784175620098
        context-author: Ramiro Ruiz
        context-author-url: https://twitter.com/ramiroruiz
        context-text: Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et ma.
        note-text: |
          Wow this is an amazing take, it makes me think a lot about that angle.
        meta-type:
        - post-meta: weather
          weather: 73.82Â°F
        - meta-link: yes
          post-meta: responses
          responses: 5
        - meta-link: yes
          post-meta: location
          location: 51Â° N, 0Â° E
        tag-item:
        - tag: Design take
        likes: 4
        comments: 1
    - name: repost (quoting)
      label: Repost (quoting)
      context:
        repost: yes
        footer: yes
        post-actions: yes
        context-avatar: https://media.ramiroruiz.com/avatars/ramiroruiz/1130549139165634566/4SXqYSCJ_bigger.png
        context-url: https://twitter.com/ramiroruiz/status/1355129784175620098
        context-author: Ramiro Ruiz
        context-author-url: https://twitter.com/ramiroruiz
        context-text: Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et ma.
        note-text: |
          Wow this is an amazing take, it makes me think a lot about that angle.
        meta-type:
        - post-meta: weather
          weather: 73.82Â°F
        - meta-link: yes
          post-meta: responses
          responses: 5
        - meta-link: yes
          post-meta: location
          location: 51Â° N, 0Â° E
        likes: 4
        comments: 1
    - name: repost
      label: Repost
      context:
        repost: yes
        footer: yes
        post-actions: yes
        context-avatar: https://media.ramiroruiz.com/avatars/ramiroruiz/1130549139165634566/4SXqYSCJ_bigger.png
        context-url: https://twitter.com/ramiroruiz/status/1355129784175620098
        context-author: Ramiro Ruiz
        context-author-url: https://twitter.com/ramiroruiz
        context-text: Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et ma.
        meta-type:
        - post-meta: weather
          weather: 73.82Â°F
        - meta-link: yes
          post-meta: responses
          responses: 2
        - meta-link: yes
          post-meta: location
          location: 51Â° N, 0Â° E
        likes: 2
    - name: photo
      label: Photo
      context:
        photo: yes
        footer: yes
        post-actions: yes
        photo-url: https://media.ramiroruiz.com/uploads/photos/2019/12/29/09-29-22/writing-at-the-couch-with-my-sleeping-kid.jpeg
        photo-alt: Writing at the couch with my sleeping kid
        note-text: |
          â™¥ï¸ these days.
        meta-type:
        - post-meta: weather
          weather: 73.82Â°F
        - meta-link: yes
          post-meta: responses
          responses: 6
        - meta-link: yes
          post-meta: location
          location: 51Â° N, 0Â° E
        likes: 4
        comments: 2
    - name: video
      label: Video
      context:
        video: yes
        footer: yes
        post-actions: yes
        video-poster: https://media.ramiroruiz.com/uploads/videos/2020/02/18/13-10-38/poster.jpg
        video-url: https://media.ramiroruiz.com/uploads/videos/2020/02/18/13-10-38/light-sparring-session.mp4
        video-alt: Light sparring session
        note-type: video
        note-text: |
          What a fun session of light sparring this morning at <a href="https://instagram.com/downtown.dojo">@downtown.dojo</a> I surely missed them.
          <em>I Cut the parts where I get hit</em> ğŸ˜†
        meta-type:
        - post-meta: weather
          weather: 73.82Â°F
        - meta-link: yes
          post-meta: responses
          responses: 3
        - meta-link: yes
          post-meta: location
          location: 51Â° N, 0Â° E
        likes: 2
        comments: 1